[package]
name = "um_server"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
um_protocol = { path = "../protocol" }
um_crypto = { path = "../crypto" }
ed25519-dalek = { version = "2", features = ["alloc"] }
tokio = { version = "1", features = ["rt-multi-thread", "net", "io-util", "sync", "macros", "time"] }
serde = { version = "1", features = ["derive"] }
postcard = { version = "1", features = ["alloc"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "net", "io-util", "sync", "macros", "time", "test-util"] }
